# Generated by Django 3.1.7 on 2021-04-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210408_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tag',
            new_name='tags',
        ),
    ]
